# Copyright (c) 2026 ZyvorAI Labs Private Limited.
# SPDX-License-Identifier: Apache-2.0
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "atlas-native.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlas-native.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "atlas-native.selectorLabels" . | nindent 6 }}
